# Generated by Django 4.2 on 2023-04-23 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product name', max_length=500)),
                ('description', models.CharField(default='Product description', max_length=2000)),
                ('seller', models.CharField(default='Product seller', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
            ],
            options={
                'unique_together': {('location_x', 'location_y')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.IntegerField(blank=True, null=True)),
                ('ups_account', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='status', max_length=500)),
                ('destination_x', models.IntegerField()),
                ('destination_y', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_packed', models.DateTimeField(blank=True, null=True)),
                ('time_loaded', models.DateTimeField(blank=True, null=True)),
                ('time_delivered', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_amazon.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_product', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_amazon.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_amazon.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'product')},
            },
        ),
        migrations.CreateModel(
            name='UserCartTuple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_product', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_amazon.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OrderProductTuple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_product', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_amazon.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_amazon.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
